
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='mate3',
    version='0.6.2',
    description='Outback Mate3s Python Library',
    python_requires='==3.*,>=3.13.0',
    project_urls={"homepage": "https://github.com/adamcharnock/mate3/", "repository": "https://github.com/adamcharnock/mate3/"},
    author='Adam Charnock',
    author_email='adam@adamcharnock.com',
    maintainer='kodonnell',
    maintainer_email='kodonnell@users.noreply.github.com',
    entry_points={"console_scripts": ["mate3 = mate3.main:main"]},
    packages=[],
    package_dir={"": "."},
    package_data={},
    install_requires=['loguru==0.*,>=0.7.3', 'pymodbus==3.*,>=3.11.1'],
    extras_require={"dev": ["black==25.*,>=25.1.0", "dephell==0.*,>=0.8.3", "flake8==7.*,>=7.3.0", "openpyxl==3.*,>=3.1.5", "pytest==8.*,>=8.4.1", "pytest-console-scripts==1.*,>=1.4.1", "pytest-dictsdiff==0.*,>=0.5.8", "pytest-subtests==0.*,>=0.14.2"]},
)
